// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'structs.freezed.dart';

// The functions `fmt`, `clone`, `eq`, `from`, `from`, `fmt`, `clone`, `eq`, `from`, `from`, `fmt`, `clone`, `eq`, `from`, `from`, `fmt`, `clone`, `eq`, `from`, `from`, `fmt`, `clone`, `eq`, `fmt`, `clone`, `eq`, `fmt`, `clone`, `eq`, `from`, `from`, `from`, `from`, `from`, `from` are not `pub`, thus are ignored.

class Amount {
  final BigInt field0;

  const Amount({
    required this.field0,
  });

  BigInt toInt() => RustLib.instance.api.crateApiStructsAmountToInt(
        that: this,
      );

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Amount &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

@freezed
sealed class OutputSpendStatus with _$OutputSpendStatus {
  const OutputSpendStatus._();

  const factory OutputSpendStatus.unspent() = OutputSpendStatus_Unspent;
  const factory OutputSpendStatus.spent(
    String field0,
  ) = OutputSpendStatus_Spent;
  const factory OutputSpendStatus.mined(
    String field0,
  ) = OutputSpendStatus_Mined;
}

class OwnedOutput {
  final int blockheight;
  final String tweak;
  final Amount amount;
  final String script;
  final String? label;
  final OutputSpendStatus spendStatus;

  const OwnedOutput({
    required this.blockheight,
    required this.tweak,
    required this.amount,
    required this.script,
    this.label,
    required this.spendStatus,
  });

  @override
  int get hashCode =>
      blockheight.hashCode ^
      tweak.hashCode ^
      amount.hashCode ^
      script.hashCode ^
      label.hashCode ^
      spendStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnedOutput &&
          runtimeType == other.runtimeType &&
          blockheight == other.blockheight &&
          tweak == other.tweak &&
          amount == other.amount &&
          script == other.script &&
          label == other.label &&
          spendStatus == other.spendStatus;
}

class Recipient {
  final String address;
  final Amount amount;
  final int nbOutputs;

  const Recipient({
    required this.address,
    required this.amount,
    required this.nbOutputs,
  });

  @override
  int get hashCode => address.hashCode ^ amount.hashCode ^ nbOutputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amount == other.amount &&
          nbOutputs == other.nbOutputs;
}

@freezed
sealed class RecordedTransaction with _$RecordedTransaction {
  const RecordedTransaction._();

  const factory RecordedTransaction.incoming(
    RecordedTransactionIncoming field0,
  ) = RecordedTransaction_Incoming;
  const factory RecordedTransaction.outgoing(
    RecordedTransactionOutgoing field0,
  ) = RecordedTransaction_Outgoing;
}

class RecordedTransactionIncoming {
  final String txid;
  final Amount amount;
  final int? confirmedAt;

  const RecordedTransactionIncoming({
    required this.txid,
    required this.amount,
    this.confirmedAt,
  });

  String toString() =>
      RustLib.instance.api.crateApiStructsRecordedTransactionIncomingToString(
        that: this,
      );

  @override
  int get hashCode => txid.hashCode ^ amount.hashCode ^ confirmedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordedTransactionIncoming &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          amount == other.amount &&
          confirmedAt == other.confirmedAt;
}

class RecordedTransactionOutgoing {
  final String txid;
  final List<String> spentOutpoints;
  final List<Recipient> recipients;
  final int? confirmedAt;

  const RecordedTransactionOutgoing({
    required this.txid,
    required this.spentOutpoints,
    required this.recipients,
    this.confirmedAt,
  });

  String toString() =>
      RustLib.instance.api.crateApiStructsRecordedTransactionOutgoingToString(
        that: this,
      );

  @override
  int get hashCode =>
      txid.hashCode ^
      spentOutpoints.hashCode ^
      recipients.hashCode ^
      confirmedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordedTransactionOutgoing &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          spentOutpoints == other.spentOutpoints &&
          recipients == other.recipients &&
          confirmedAt == other.confirmedAt;
}

class WalletStatus {
  final String address;
  final BigInt balance;
  final int birthday;
  final int lastScan;
  final Map<String, OwnedOutput> outputs;
  final List<RecordedTransaction> txHistory;

  const WalletStatus({
    required this.address,
    required this.balance,
    required this.birthday,
    required this.lastScan,
    required this.outputs,
    required this.txHistory,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      balance.hashCode ^
      birthday.hashCode ^
      lastScan.hashCode ^
      outputs.hashCode ^
      txHistory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletStatus &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          balance == other.balance &&
          birthday == other.birthday &&
          lastScan == other.lastScan &&
          outputs == other.outputs &&
          txHistory == other.txHistory;
}
