// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'constants.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.io.dart' if (dart.library.html) 'frb_generated.web.dart';
import 'logger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'stream.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0-dev.37';

  @override
  int get rustContentHash => -579847335;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_donationwallet',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiSimpleAddFeeForFeeRate(
      {required String psbt, required int feeRate, required String payer});

  Future<String> crateApiSimpleBroadcastTx({required String tx});

  Future<void> crateApiSimpleChangeBirthday(
      {required String path, required String label, required int birthday});

  Stream<BigInt> crateApiSimpleCreateAmountStream();

  Stream<LogEntry> crateApiSimpleCreateLogStream(
      {required LogLevel level, required bool logDependencies});

  Future<String> crateApiSimpleCreateNewPsbt(
      {required String label,
      required String path,
      required List<OwnedOutput> inputs,
      required List<Recipient> recipients});

  Stream<ScanProgress> crateApiSimpleCreateScanProgressStream();

  Stream<SyncStatus> crateApiSimpleCreateSyncStream();

  Future<String> crateApiSimpleExtractTxFromPsbt({required String psbt});

  Future<String> crateApiSimpleFillSpOutputs(
      {required String path, required String label, required String psbt});

  Future<List<OwnedOutput>> crateApiSimpleGetOutputs(
      {required String path, required String label});

  Future<String> crateApiSimpleGetReceivingAddress(
      {required String path, required String label});

  Future<List<OwnedOutput>> crateApiSimpleGetSpendableOutputs(
      {required String path, required String label});

  Future<WalletStatus> crateApiSimpleGetWalletInfo(
      {required String path, required String label});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimpleMarkTransactionInputsAsSpent(
      {required String path, required String label, required String tx});

  Future<void> crateApiSimpleRemoveWallet(
      {required String path, required String label});

  Future<void> crateApiSimpleResetWallet(
      {required String path, required String label});

  Future<void> crateApiSimpleScanToTip(
      {required String path, required String label});

  Future<String> crateApiSimpleSetup(
      {required String label,
      required String filesDir,
      required WalletType walletType,
      required int birthday,
      required bool isTestnet});

  Future<String?> crateApiSimpleShowMnemonic(
      {required String path, required String label});

  Future<String> crateApiSimpleSignPsbt(
      {required String path,
      required String label,
      required String psbt,
      required bool finalize});

  Future<void> crateApiSimpleSyncBlockchain();

  Future<bool> crateApiSimpleWalletExists(
      {required String label, required String filesDir});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiSimpleAddFeeForFeeRate(
      {required String psbt, required int feeRate, required String payer}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(psbt, serializer);
        sse_encode_u_32(feeRate, serializer);
        sse_encode_String(payer, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleAddFeeForFeeRateConstMeta,
      argValues: [psbt, feeRate, payer],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleAddFeeForFeeRateConstMeta =>
      const TaskConstMeta(
        debugName: "add_fee_for_fee_rate",
        argNames: ["psbt", "feeRate", "payer"],
      );

  @override
  Future<String> crateApiSimpleBroadcastTx({required String tx}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(tx, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleBroadcastTxConstMeta,
      argValues: [tx],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleBroadcastTxConstMeta => const TaskConstMeta(
        debugName: "broadcast_tx",
        argNames: ["tx"],
      );

  @override
  Future<void> crateApiSimpleChangeBirthday(
      {required String path, required String label, required int birthday}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        sse_encode_u_32(birthday, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleChangeBirthdayConstMeta,
      argValues: [path, label, birthday],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleChangeBirthdayConstMeta =>
      const TaskConstMeta(
        debugName: "change_birthday",
        argNames: ["path", "label", "birthday"],
      );

  @override
  Stream<BigInt> crateApiSimpleCreateAmountStream() {
    final s = RustStreamSink<BigInt>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_u_64_Sse(s, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleCreateAmountStreamConstMeta,
      argValues: [s],
      apiImpl: this,
    )));
    return s.stream;
  }

  TaskConstMeta get kCrateApiSimpleCreateAmountStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_amount_stream",
        argNames: ["s"],
      );

  @override
  Stream<LogEntry> crateApiSimpleCreateLogStream(
      {required LogLevel level, required bool logDependencies}) {
    final s = RustStreamSink<LogEntry>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_log_entry_Sse(s, serializer);
        sse_encode_log_level(level, serializer);
        sse_encode_bool(logDependencies, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleCreateLogStreamConstMeta,
      argValues: [s, level, logDependencies],
      apiImpl: this,
    )));
    return s.stream;
  }

  TaskConstMeta get kCrateApiSimpleCreateLogStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_log_stream",
        argNames: ["s", "level", "logDependencies"],
      );

  @override
  Future<String> crateApiSimpleCreateNewPsbt(
      {required String label,
      required String path,
      required List<OwnedOutput> inputs,
      required List<Recipient> recipients}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(label, serializer);
        sse_encode_String(path, serializer);
        sse_encode_list_owned_output(inputs, serializer);
        sse_encode_list_recipient(recipients, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateNewPsbtConstMeta,
      argValues: [label, path, inputs, recipients],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateNewPsbtConstMeta =>
      const TaskConstMeta(
        debugName: "create_new_psbt",
        argNames: ["label", "path", "inputs", "recipients"],
      );

  @override
  Stream<ScanProgress> crateApiSimpleCreateScanProgressStream() {
    final s = RustStreamSink<ScanProgress>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_scan_progress_Sse(s, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleCreateScanProgressStreamConstMeta,
      argValues: [s],
      apiImpl: this,
    )));
    return s.stream;
  }

  TaskConstMeta get kCrateApiSimpleCreateScanProgressStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_scan_progress_stream",
        argNames: ["s"],
      );

  @override
  Stream<SyncStatus> crateApiSimpleCreateSyncStream() {
    final s = RustStreamSink<SyncStatus>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_sync_status_Sse(s, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleCreateSyncStreamConstMeta,
      argValues: [s],
      apiImpl: this,
    )));
    return s.stream;
  }

  TaskConstMeta get kCrateApiSimpleCreateSyncStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_sync_stream",
        argNames: ["s"],
      );

  @override
  Future<String> crateApiSimpleExtractTxFromPsbt({required String psbt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(psbt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleExtractTxFromPsbtConstMeta,
      argValues: [psbt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleExtractTxFromPsbtConstMeta =>
      const TaskConstMeta(
        debugName: "extract_tx_from_psbt",
        argNames: ["psbt"],
      );

  @override
  Future<String> crateApiSimpleFillSpOutputs(
      {required String path, required String label, required String psbt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        sse_encode_String(psbt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleFillSpOutputsConstMeta,
      argValues: [path, label, psbt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleFillSpOutputsConstMeta =>
      const TaskConstMeta(
        debugName: "fill_sp_outputs",
        argNames: ["path", "label", "psbt"],
      );

  @override
  Future<List<OwnedOutput>> crateApiSimpleGetOutputs(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_owned_output,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetOutputsConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetOutputsConstMeta => const TaskConstMeta(
        debugName: "get_outputs",
        argNames: ["path", "label"],
      );

  @override
  Future<String> crateApiSimpleGetReceivingAddress(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetReceivingAddressConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetReceivingAddressConstMeta =>
      const TaskConstMeta(
        debugName: "get_receiving_address",
        argNames: ["path", "label"],
      );

  @override
  Future<List<OwnedOutput>> crateApiSimpleGetSpendableOutputs(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_owned_output,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetSpendableOutputsConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetSpendableOutputsConstMeta =>
      const TaskConstMeta(
        debugName: "get_spendable_outputs",
        argNames: ["path", "label"],
      );

  @override
  Future<WalletStatus> crateApiSimpleGetWalletInfo(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_wallet_status,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetWalletInfoConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetWalletInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_wallet_info",
        argNames: ["path", "label"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleMarkTransactionInputsAsSpent(
      {required String path, required String label, required String tx}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        sse_encode_String(tx, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleMarkTransactionInputsAsSpentConstMeta,
      argValues: [path, label, tx],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleMarkTransactionInputsAsSpentConstMeta =>
      const TaskConstMeta(
        debugName: "mark_transaction_inputs_as_spent",
        argNames: ["path", "label", "tx"],
      );

  @override
  Future<void> crateApiSimpleRemoveWallet(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleRemoveWalletConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleRemoveWalletConstMeta => const TaskConstMeta(
        debugName: "remove_wallet",
        argNames: ["path", "label"],
      );

  @override
  Future<void> crateApiSimpleResetWallet(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleResetWalletConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleResetWalletConstMeta => const TaskConstMeta(
        debugName: "reset_wallet",
        argNames: ["path", "label"],
      );

  @override
  Future<void> crateApiSimpleScanToTip(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleScanToTipConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleScanToTipConstMeta => const TaskConstMeta(
        debugName: "scan_to_tip",
        argNames: ["path", "label"],
      );

  @override
  Future<String> crateApiSimpleSetup(
      {required String label,
      required String filesDir,
      required WalletType walletType,
      required int birthday,
      required bool isTestnet}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(label, serializer);
        sse_encode_String(filesDir, serializer);
        sse_encode_box_autoadd_wallet_type(walletType, serializer);
        sse_encode_u_32(birthday, serializer);
        sse_encode_bool(isTestnet, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetupConstMeta,
      argValues: [label, filesDir, walletType, birthday, isTestnet],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetupConstMeta => const TaskConstMeta(
        debugName: "setup",
        argNames: ["label", "filesDir", "walletType", "birthday", "isTestnet"],
      );

  @override
  Future<String?> crateApiSimpleShowMnemonic(
      {required String path, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleShowMnemonicConstMeta,
      argValues: [path, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleShowMnemonicConstMeta => const TaskConstMeta(
        debugName: "show_mnemonic",
        argNames: ["path", "label"],
      );

  @override
  Future<String> crateApiSimpleSignPsbt(
      {required String path,
      required String label,
      required String psbt,
      required bool finalize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(label, serializer);
        sse_encode_String(psbt, serializer);
        sse_encode_bool(finalize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSignPsbtConstMeta,
      argValues: [path, label, psbt, finalize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSignPsbtConstMeta => const TaskConstMeta(
        debugName: "sign_psbt",
        argNames: ["path", "label", "psbt", "finalize"],
      );

  @override
  Future<void> crateApiSimpleSyncBlockchain() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSyncBlockchainConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSyncBlockchainConstMeta =>
      const TaskConstMeta(
        debugName: "sync_blockchain",
        argNames: [],
      );

  @override
  Future<bool> crateApiSimpleWalletExists(
      {required String label, required String filesDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(label, serializer);
        sse_encode_String(filesDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleWalletExistsConstMeta,
      argValues: [label, filesDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWalletExistsConstMeta => const TaskConstMeta(
        debugName: "wallet_exists",
        argNames: ["label", "filesDir"],
      );

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SyncStatus> dco_decode_StreamSink_sync_status_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<BigInt> dco_decode_StreamSink_u_64_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  WalletType dco_decode_box_autoadd_wallet_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wallet_type(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<OwnedOutput> dco_decode_list_owned_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_owned_output).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_recipient).toList();
  }

  @protected
  LogEntry dco_decode_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LogEntry(
      timeMillis: dco_decode_i_64(arr[0]),
      level: dco_decode_String(arr[1]),
      tag: dco_decode_String(arr[2]),
      msg: dco_decode_String(arr[3]),
    );
  }

  @protected
  LogLevel dco_decode_log_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LogLevel.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  OutputSpendStatus dco_decode_output_spend_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return OutputSpendStatus_Unspent();
      case 1:
        return OutputSpendStatus_Spent(
          dco_decode_String(raw[1]),
        );
      case 2:
        return OutputSpendStatus_Mined(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  OwnedOutput dco_decode_owned_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return OwnedOutput(
      txoutpoint: dco_decode_String(arr[0]),
      blockheight: dco_decode_u_32(arr[1]),
      tweak: dco_decode_String(arr[2]),
      amount: dco_decode_u_64(arr[3]),
      script: dco_decode_String(arr[4]),
      label: dco_decode_opt_String(arr[5]),
      spendStatus: dco_decode_output_spend_status(arr[6]),
    );
  }

  @protected
  Recipient dco_decode_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Recipient(
      address: dco_decode_String(arr[0]),
      amount: dco_decode_u_64(arr[1]),
      nbOutputs: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScanProgress(
      start: dco_decode_u_32(arr[0]),
      current: dco_decode_u_32(arr[1]),
      end: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SyncStatus(
      blockheight: dco_decode_u_32(arr[0]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WalletStatus dco_decode_wallet_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WalletStatus(
      amount: dco_decode_u_64(arr[0]),
      birthday: dco_decode_u_32(arr[1]),
      scanHeight: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  WalletType dco_decode_wallet_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return WalletType_New();
      case 1:
        return WalletType_Mnemonic(
          dco_decode_String(raw[1]),
        );
      case 2:
        return WalletType_PrivateKeys(
          dco_decode_String(raw[1]),
          dco_decode_String(raw[2]),
        );
      case 3:
        return WalletType_ReadOnly(
          dco_decode_String(raw[1]),
          dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SyncStatus> sse_decode_StreamSink_sync_status_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<BigInt> sse_decode_StreamSink_u_64_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  WalletType sse_decode_box_autoadd_wallet_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wallet_type(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<OwnedOutput> sse_decode_list_owned_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OwnedOutput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_owned_output(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Recipient>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recipient(deserializer));
    }
    return ans_;
  }

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeMillis = sse_decode_i_64(deserializer);
    var var_level = sse_decode_String(deserializer);
    var var_tag = sse_decode_String(deserializer);
    var var_msg = sse_decode_String(deserializer);
    return LogEntry(
        timeMillis: var_timeMillis,
        level: var_level,
        tag: var_tag,
        msg: var_msg);
  }

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LogLevel.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OutputSpendStatus sse_decode_output_spend_status(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return OutputSpendStatus_Unspent();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return OutputSpendStatus_Spent(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return OutputSpendStatus_Mined(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  OwnedOutput sse_decode_owned_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txoutpoint = sse_decode_String(deserializer);
    var var_blockheight = sse_decode_u_32(deserializer);
    var var_tweak = sse_decode_String(deserializer);
    var var_amount = sse_decode_u_64(deserializer);
    var var_script = sse_decode_String(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    var var_spendStatus = sse_decode_output_spend_status(deserializer);
    return OwnedOutput(
        txoutpoint: var_txoutpoint,
        blockheight: var_blockheight,
        tweak: var_tweak,
        amount: var_amount,
        script: var_script,
        label: var_label,
        spendStatus: var_spendStatus);
  }

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_amount = sse_decode_u_64(deserializer);
    var var_nbOutputs = sse_decode_u_32(deserializer);
    return Recipient(
        address: var_address, amount: var_amount, nbOutputs: var_nbOutputs);
  }

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_u_32(deserializer);
    var var_current = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    return ScanProgress(start: var_start, current: var_current, end: var_end);
  }

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blockheight = sse_decode_u_32(deserializer);
    return SyncStatus(blockheight: var_blockheight);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WalletStatus sse_decode_wallet_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_amount = sse_decode_u_64(deserializer);
    var var_birthday = sse_decode_u_32(deserializer);
    var var_scanHeight = sse_decode_u_32(deserializer);
    return WalletStatus(
        amount: var_amount, birthday: var_birthday, scanHeight: var_scanHeight);
  }

  @protected
  WalletType sse_decode_wallet_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return WalletType_New();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return WalletType_Mnemonic(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        var var_field1 = sse_decode_String(deserializer);
        return WalletType_PrivateKeys(var_field0, var_field1);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        var var_field1 = sse_decode_String(deserializer);
        return WalletType_ReadOnly(var_field0, var_field1);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
      RustStreamSink<LogEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
                decodeSuccessData: sse_decode_log_entry,
                decodeErrorData: null)),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
      RustStreamSink<ScanProgress> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
                decodeSuccessData: sse_decode_scan_progress,
                decodeErrorData: null)),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_sync_status_Sse(
      RustStreamSink<SyncStatus> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
                decodeSuccessData: sse_decode_sync_status,
                decodeErrorData: null)),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_u_64_Sse(
      RustStreamSink<BigInt> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
                decodeSuccessData: sse_decode_u_64, decodeErrorData: null)),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_wallet_type(
      WalletType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wallet_type(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_owned_output(
      List<OwnedOutput> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_owned_output(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_recipient(
      List<Recipient> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recipient(item, serializer);
    }
  }

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timeMillis, serializer);
    sse_encode_String(self.level, serializer);
    sse_encode_String(self.tag, serializer);
    sse_encode_String(self.msg, serializer);
  }

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_output_spend_status(
      OutputSpendStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case OutputSpendStatus_Unspent():
        sse_encode_i_32(0, serializer);
      case OutputSpendStatus_Spent(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case OutputSpendStatus_Mined(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_owned_output(OwnedOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txoutpoint, serializer);
    sse_encode_u_32(self.blockheight, serializer);
    sse_encode_String(self.tweak, serializer);
    sse_encode_u_64(self.amount, serializer);
    sse_encode_String(self.script, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_output_spend_status(self.spendStatus, serializer);
  }

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_64(self.amount, serializer);
    sse_encode_u_32(self.nbOutputs, serializer);
  }

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.current, serializer);
    sse_encode_u_32(self.end, serializer);
  }

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.blockheight, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wallet_status(WalletStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.amount, serializer);
    sse_encode_u_32(self.birthday, serializer);
    sse_encode_u_32(self.scanHeight, serializer);
  }

  @protected
  void sse_encode_wallet_type(WalletType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case WalletType_New():
        sse_encode_i_32(0, serializer);
      case WalletType_Mnemonic(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case WalletType_PrivateKeys(field0: final field0, field1: final field1):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
        sse_encode_String(field1, serializer);
      case WalletType_ReadOnly(field0: final field0, field1: final field1):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
        sse_encode_String(field1, serializer);
    }
  }
}
